ELIMINACIÓN GAUSSIANA

In [13]:
#Escriba un código de eliminación Gaussiana para resolver el sistema Ax=b.

import numpy as np
N=np.random.randint(3, 7)
Arreglo=(np.random.random((N,N))*10.0)-5.0
b=(np.random.random((N,1))*10.0)-5.0

for i in range(N):
    b[i] = b[i]/Arreglo[i,i]
    Arreglo[i,:] = Arreglo[i,:]/Arreglo[i,i]
    for j in range(i+1,N):
        b[j] = b[j] - b[i]*Arreglo[j,i]
        Arreglo[j,:] = Arreglo[j,:] - Arreglo[j,i]*Arreglo[i,:]





print(Arreglo)
print(b)
#compare sus resultados con el paquete de numpy:
#https://numpy.org/doc/stable/reference/generated/numpy.linalg.solve.html

[[ 1.         -0.68973867 -1.49276205]
 [ 0.          1.          1.20707282]
 [-0.         -0.          1.        ]]
[[ 2.25664714]
 [-2.57831183]
 [-1.52610544]]
